### ISSUE TITLE
power consumption and performance 

### ISSUE THREAD

**Issue by zkriahac** [punchagan/GetHub#10]
x86 architecture is one of the widely used embedded computing platform if power consumption is not an issue. 
reason ??

may be !!

x86 arc has clock speed more than 3.5 GH And a had an ISA , those make the x86 in the first from performance , but when we goes to the power consumption we know that high clock lead to use high power (drop voltage) , and this issue  make it out offside the tablet and mobile  , while the ARM has low power consumption but it proportion to tablet

**Comment by punchagan** [comment]
Spam?
