### ISSUE TITLE
Specify github hostname?

### ISSUE THREAD

**Issue by dkerwin** [punchagan/GetHub#4]
Some users run a local Github:FI install. If the github hostname could be specified in the options i could use your great plugin for the internal Github too.

**Comment by punchagan** [comment]
That's a neat idea and shouldn't be too hard to do. Can you send an example
of the url? (use example.com, instead of the actual domain name)
On Nov 7, 2011 10:40 PM, "Daniel Kerwin" <
reply@reply.github.com>
wrote:

**Comment by dkerwin** [comment]
In fact it's exactly the same URL except for the hostname. Something like this:

http(s)://github.example.com/USERNAME.private.atom?token=123456......

So the options page should accept the domain including http(s)://. It would be perfect if one could specify more than one github server to get external and internal notifications.

**Comment by dkerwin** [comment]
Awesome. Thank you!
