### ISSUE TITLE
Github token no longer available

### ISSUE THREAD

**Issue by omnikron** [punchagan/GetHub#5]
Github has recently removed the API v2 token from the github profile in preparation for their v3 API (which will use OAuth 2 instead).  As far as I can see, anybody who didn't have this token saved elsewhere can no longer start using Gethub.

Would it be possible to implement OAuth for Gethub as well?  My javascript is weak so there's no code attached I'm afraid, but the relevant API page is: http://developer.github.com/v3/events/

**Comment by punchagan** [comment]
The token can be obtained from the link to `News Feed` on the dashboard (top right corner)

**Comment by omnikron** [comment]
Yep, I realise also that it's in ~/.gitconfig as long as you've set git up according to github's setup guide.  Just a documentation change then!

**Comment by punchagan** [comment]
Ah, I was hoping you'd send in a patch. :P
I'll make a change.

**Comment by omnikron** [comment]
:bowtie:
