### ISSUE TITLE
User Profile Images

### ISSUE THREAD

**Issue by JamieMason** [punchagan/GetHub#8]
Hey @punchagan, great extension, I really like it.

I don't know if Chrome supports this, but if it is it would be cool if you can show the profile image of the user which triggered the notification, instead of the Google Chrome logo.

Thanks a lot.

**Comment by punchagan** [comment]
Hey @JamieMason, thanks for writing back.  I'm not sure if the API has changed, but it wasn't supported when this extension was written.  I'll take a look, if and when I get a chance.

**Comment by JamieMason** [comment]
That's great, whenever you get time of course.

I just took a look now actually out of curiosity and it appears to be available now;

```
Properties of NotificationOptions

    iconUrl ( string )
    Sender's avatar, app icon, or a thumbnail for image notifications.
```

https://developer.chrome.com/extensions/notifications.html#type-NotificationOptions

**Comment by punchagan** [comment]
Thanks for digging it up! I'd gladly accept a Pull-request, if you are interested!  Otherwise, this'll have to wait a bit, I guess.

**Comment by JamieMason** [comment]
Sure, I've not worked on an extension before though - I'll read up on how you work on and test them.

**Comment by punchagan** [comment]
Great! Let me know, if you need any help. :)

**Comment by punchagan** [comment]
@JamieMason Try updating the extension and you should see the user images! :)

**Comment by JamieMason** [comment]
Great! will do, thanks
